name: Deploy to test server

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull latest on server
        run: |
          cd /home/wonsec/CertHub-prototype-web
          git pull origin main
